name: get-emacs-and-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 27.2
      - uses: actions/checkout@v2
      - name: Get emacs testing library buttercup
        run: 'emacs --batch --script cisetup.el'
      - name: Run tests
        run: 'emacs --batch -f package-initialize -L . -f buttercup-run-discover'