name: test-github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 27.2
      - uses: actions/checkout@v2
      - name: Get emacs testing library buttercup
        run: 'emacs --batch --script ./../../cisetup.el'